version: '3'
 
services:
    app_1:
        container_name: app-1
        build: ./app-1
        ports: 
          - 8080:80
    app_2:
        container_name: app-2
        build: ./app-2
        ports:
          - 9090:80
    haproxy_img:
        container_name: proxy
        build: ./proxy
        ports:
          - 80:80
